# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [36]:
A = np.arange(1, 16).reshape(3,5)

In [37]:
print("This:\n", A, "\nis an array with", A.ndim, "axes and the dimension", A.shape, ".\nIt has", A.size, "elements of the", A.dtype,"type.")


This:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 
is an array with 2 axes and the dimension (3, 5) .
It has 15 elements of the int32 type.


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [40]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [49]:
difference = B - C
print(difference)
print()

total = B + C
print(total)
print()

elementwise_product = B * C
print(elementwise_product)
print()

matrix_product = B @ C
print(matrix_product)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [50]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
exponentiated = np.exp(B)
print(exponentiated)

min_value = B.min()
max_value = B.max()
print("The minimum value of the array is", min_value, "and the maximum is", max_value, ".")

min_row = np.min(B, axis=1)
min_col = np.min(B, axis=0)
print("The minimal values per row are", min_row, "and the minimal values per column are", min_col, ".")

index_min = np.argmin(B)
index_min_row = np.argmin(B, axis=1)
print("The index of the minimal value is", index_min, "and the index of the minimal values per row are", index_min_row, ".")

sum_of_elements = np.sum(B)
print("The sum of all elements is", sum_of_elements, ".")

mean_col = np.mean(B, axis=0)
median_col = np.median(B, axis=0)
print("The means per column are", mean_col, "and the medians per column are", median_col, ".")

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
The minimum value of the array is 1 and the maximum is 9 .
The minimal values per row are [1 4 7] and the minimal values per column are [1 2 3] .
The index of the minimal value is 0 and the index of the minimal values per row are [0 0 0] .
The sum of all elements is 45 .
The means per column are [4. 5. 6.] and the medians per column are [4. 5. 6.] .


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [81]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [82]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

#### It means I want all of the elements along that axis.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [84]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [83]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [85]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### Three axes means the matrix stretches in three dimensions. The code creates a one-dimensional array with 30 elements, reshapes it into a three-dimensional matrix and then prints it.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [86]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [87]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [91]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print(A+b)

[[1 2]
 [3 4]]
[2 2]
[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [92]:
def check_if_matrix(matrix):
    if not isinstance(matrix, np.ndarray):
        raise TypeError ("A NumPy array is expected as argument.")
    
def check_matrix_size(matrix1, matrix2):
     if matrix1.size != matrix2.size:
          raise ValueError("Matrices are not of equal size.")

def add_mult_matrices(matrix1, matrix2, choice):
    check_if_matrix(matrix1), check_if_matrix(matrix2)
    if (choice == "add"):
            return matrix1 + matrix2
    elif (choice == "multiply"):
        check_matrix_size(matrix1, matrix2)
        return matrix1 @ matrix2
    raise ValueError("Choose 'add' or 'multiply', please")

In [101]:
F = np.array([[1, 2], [3, 8]])
G = np.array([[5, 6], [7, 8]])
add_mult_matrices(F, G, "multiply")

array([[19, 22],
       [71, 82]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [120]:
# 10.1.1
x = np.array([4, 3])

a = x.shape
b = 5*x
c = 3*x
d = 5*x+3*x
e = 8*x
f = 4*x-x
g = x.T
g.shape
h = x-g # Answer: No but NumPy makes their dimensions match by broadcasting the smaller array.
i = np.linalg.norm(x)

In [132]:
# 10.1.2
v = np.array([[3], [7], [0], [11]])

a = v.shape
b = 2*v
c = 5*v+2*v
d = 4*v-2*v
e = v.T
e.shape
f = np.linalg.norm(v)

In [142]:
# 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
v1.shape
v2.shape

a = np.linalg.norm(v1)
b = np.linalg.norm(v1-v2)

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [173]:
# 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

a = 2*A
b = B-a
c = 3*C-2*E # Undefined, NumPy will broadcast.
e = D.T+2*D
f = 2*C.T-2*D.T
# g = A.T-B is undefined and not suitable for broadcast.
# h = A@C is undefined.
i = C@D
j = C@B
k = C@I
l = A@B.T

[[5 2]
 [7 4]]


In [176]:
# 10.2.2
A = np.array([[2, 3, 4], [3, 4, 1]])
print(A@A.T)

[[29 22]
 [22 26]]


In [184]:
# 10.2.3
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(A@B == A@C)
print(B == C)

[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [189]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)